---
# tasks file for postfix
- name: Load the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install postfix packages
  package: 
    name: '{{ postfix_pkgs }}'
    state: present

- name: Get postfix version
  check_mode: false
  changed_when: false
  shell: 'postconf mail_version | sed -e "s/mail_version = \([0-9]\)\.\([0-9]\)\.\([0-9]\{1,2\}\).*/\1/"'
  register: postfix_version

- name: Load postfix configuration files
  tags: postfix
  template: 
    src: "{{ item + '.j2' }}"
    dest: "/etc/postfix/{{ item }}"
    owner: root
    group: root
    mode: 0644
    setype: postfix_etc_t
    serole: object_r
    seuser: system_u
    backup: yes
  with_items:
    - main.cf
    - master.cf
  notify:
    - restart postfix

- name: Load /etc/mailname on Debian systems
  tags: postfix
  template: src=mailname.j2 dest=/etc/mailname owner=root group=root mode=0644
  notify: regenerate aliases
  when: ansible_os_family == 'Debian'

- name: Load aliases file
  tags: postfix
  template:
    src: "{{ item }}"
    dest: "/etc/aliases"
    owner: "root"
    group: "root"
    mode: 0644
    setype: etc_aliases_t
    serole: object_r
    seuser: system_u
    backup: yes
  with_first_found:
    - "aliases.{{ ansible_os_family }},j2"
    - "aliases.j2"
  notify: regenerate aliases

- name: Load aditional configuration
  tags: postfix
  template: src={{ item + '.j2' }} dest=/etc/postfix/{{ item }} owner=root group=root mode=0600
  with_items:
    - "transport"
    - "sasl_passwd"
    - "sender_relay"
  notify: 
    - regenerate maps

- name: Ensure postfix is running.
  tags: postfix
  service: name={{ postfix_service }} state=started enabled=yes
