---
# handlers file for postfix
- name: reload postfix
  tags: postfix
  action: service name=postfix state=reloaded

- name: restart postfix
  tags: postfix
  service: name=postfix state=restarted

- name: regenerate aliases
  tags: postfix
  command: newaliases

- name: regenerate maps
  tags: postfix
  command: "{{ item }}"
  with_items: 
    - postmap /etc/postfix/transport
    - postmap /etc/postfix/sasl_passwd

